name: swim-adsb
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - pip:
      - git+https://git@github.com/kjenod/rest-client.git
      - git+https://git@github.com/kjenod/opensky-network-client.git
      - git+https://git@github.com/kjenod/subscription-manager-client.git
      - git+https://git@github.com/kjenod/swim-qpid-proton.git
      - git+https://git@github.com/kjenod/pubsub-facades.git
      - git+https://git@github.com/kjenod/swim-backend.git
      - python-qpid_proton
      - cachetools
